name: envase_20litros
description: Aplicação para gerenciamento de envase de garrafões de 20 litros.
version: 1.0.0
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  dotenv: ^7.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  logger: ^1.3.0
  mysql1: ^0.20.0
  intl: ^0.18.0
  provider: ^6.0.5
  pdf: ^3.11.0
  printing: ^5.11.0
flutter:
  assets:
    - assets/logo_aguas_giovanna.jpg
  uses-material-design: true
